Creating OrderDetails entity.
josera980/Tasty-Yaroa pull request #11
Opened 2023-03-26 14:01 UTC by josera980

Creating new entity: OrderDetails

2023-03-26 19:03 UTC, reynoldmorel requested changes

2023-03-26 19:03 UTC, reynoldmorel commented on src/entities/OrderDetails.js
> +        this.id - id;
Is this a typo?

2023-03-26 19:03 UTC, reynoldmorel commented on src/entities/OrderDetails.js
> +export class OrderDetails {
`OrderDetail`?

2023-03-26 20:45 UTC, josera980 commented on src/entities/OrderDetails.js
> +export class OrderDetails {
Fixed the typo and renamed class.

2023-04-02 14:04 UTC, reynoldmorel approved these changes

2023-04-07 13:22 UTC, merged