Feature/create ingredient entity
josera980/Tasty-Yaroa pull request #7
Opened 2023-03-22 14:06 UTC by josera980

Creating the Ingredient class.

2023-03-22 14:44 UTC, reynoldmorel requested changes

2023-03-22 14:44 UTC, reynoldmorel commented on src/entities/Ingredient.js
> +    constructor(id, name, stock, cost) {
Is it the same cost and price? You have price for dish and cost for ingredient

2023-03-22 14:51 UTC, josera980 commented on src/entities/Ingredient.js
> +    constructor(id, name, stock, cost) {
Cost refers to the amount of money the restaurant gives to buy the ingredient (which is not for sale here). Price refers to the amount we sell the dish to the clients.

2023-03-23 01:47 UTC, reynoldmorel approved these changes

2023-03-23 02:09 UTC, merged